import json
import os
import time  # <-- Added for high-precision timing
from resistor_llm.fireworks_client import ask_llm
from resistor_llm.prompt_templates import build_report_prompt
from resistor_llm.output_validator import is_valid_llm_output

def load_gnn_results():
    # Load the JSON we generated in Part 9
    json_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../resistor_output.json'))
    with open(json_path, 'r') as f:
        return json.load(f)

def generate_final_report():
    print("--- RESISTOR: LLM Report Generator ---")
    
    # 1. Load Data
    data = load_gnn_results()
    
    # 2. Build Prompt
    prompt = build_report_prompt(data['target'], data['top_mutations'])
    print("[INFO] Prompt built successfully. Sending to Fireworks API...")
    
    # 3. Call API and Measure Response Time
    start_time = time.perf_counter()
    
    llm_response = ask_llm(prompt, timeout=15.0)
    
    api_duration = time.perf_counter() - start_time
    print(f"[INFO] ⏱️ API Call completed in {api_duration:.2f} seconds")
    
    # 4. Validate Output
    if is_valid_llm_output(llm_response):
        print("[SUCCESS] Valid report generated by LLM.")
        report = llm_response
    else:
        print("[WARNING] LLM output invalid or timed out. Using cached fallback report.")
        report = get_cached_report()
        
    # 5. Save the final UI payload
    data['executive_summary'] = report
    
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../dashboard_payload.json'))
    with open(out_path, 'w') as f:
        json.dump(data, f, indent=4)
        
    print(f"[SUCCESS] Final Dashboard Payload saved to {out_path}")
    print("\n--- EXECUTIVE SUMMARY ---")
    print(report)

def get_cached_report():
    """Fallback cache (Item 8)"""
    cache_path = os.path.join(os.path.dirname(__file__), 'cached_reports', 'fallback_report.txt')
    if os.path.exists(cache_path):
        with open(cache_path, 'r') as f:
            return f.read()
    return "Error: Could not reach AI reasoning engine. Top structural threats are D27E and the known clinical resistance mutation F98Y. Both present highly stable, high-disruption binding profiles requiring immediate pharmaceutical review."

if __name__ == "__main__":
    generate_final_report()